apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "{{ .Release.Name }}.{{ .Values.ingressControllerIP }}.nip.io"
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-poi
          servicePort: {{ .Values.poi.service.port }}
        path: /api/poi/
      - backend:
          serviceName: {{ .Release.Name }}-trips
          servicePort: {{ .Values.trips.service.port }}
        path: /api/trips/
      - backend:
          serviceName: {{ .Release.Name }}-user-java
          servicePort: {{ $userjava := index .Values "user-java"}}{{ $userjava.service.port }}
        path: /api/user-java/
      - backend:
          serviceName: {{ .Release.Name }}-user-profile
          servicePort: {{ $userprof := index .Values "user-profile"}}{{ $userprof.service.port }}
        path: /api/user/